## Video
profile=high-quality
vo=gpu-next
gpu-api=vulkan
scale-antiring=0.6
#Hardware decoding for whatever your CPU/GPU supports (e.g. 8bit h264 / 10bit h265)
#Use "auto-safe" or "auto-copy-safe"
#"Copy" methods are safer to use, but the performance difference is probably not as high and maybe not even worth over "no" (disabled).
#Manual options:
#Nvidia GPU: "nvdec"/"nvdec-copy" (Recommended)
#Windows: "dxva2-copy" or "vulkan"/"vulkan-copy"
#Linux: "vaapi"/"vaapi-copy" or "vulkan"/"vulkan-copy"
#Else "no" and disable it
hwdec=nvdec

#Default volume of the player
volume=75
#Load external audio with (almost) the same name as the video
audio-file-auto=fuzzy

# Dither
# This must be set to match your monitor's bit depth
dither-depth = 8

## Behavior (personal preference)
keep-open=yes
save-position-on-quit=yes
autofit=75%
border=no
# volume bar
osd-bar=no

## Screenshots
screenshot-format=png
screenshot-dir="~/Pictures/mpv"
screenshot-template="%F-%p-%n"
screenshot-high-bit-depth=no

## Language Priority
## Sub
## Add enm before eng for honorifics
slang=eng,en
alang=jpn,ja,en,eng
